In [4]:
import numpy as np

In [5]:
mya=np.array([11,25,36,89])
mys

array([11, 25, 36, 89])

In [7]:
myb=np.array([11,25,36,89],dtype=complex)
for i in myb:
    print(i)

(11+0j)
(25+0j)
(36+0j)
(89+0j)


In [11]:
myc=np.array([[11,25,36,89],[20,50,60,90]])
print(myc)
myc[1][2]

[[11 25 36 89]
 [20 50 60 90]]


np.int64(60)

In [14]:
myd=np.zeros(6)
mye=np.zeros((3,3),dtype=int)
myf=np.ones(((6,4)))
myg=np.empty((2,4))
print(myd)
print(mye)
print(myf)
print(myg)


[0. 0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5.43e-323 1.24e-322 1.78e-322 4.40e-322]
 [9.88e-323 2.47e-322 2.96e-322 4.45e-322]]


In [21]:
np1=np.arange(1,100,2)
np2=np.linspace(0,8,10)
print(np1)
print(np2)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[0.         0.88888889 1.77777778 2.66666667 3.55555556 4.44444444
 5.33333333 6.22222222 7.11111111 8.        ]


In [35]:
np3=np.array([[8,6,5.2],[72,-12,3.9]])
print(np3)
print(np3[0])
print(np3[0,1])
print(np3[1,2])
print(np3[:,2])#索引中的的形式是[*,*]的形式，：的意思是代表了全部，比如[：，2]是第三列，[1,:]是代表前两行
print(np3[1,:])

[[  8.    6.    5.2]
 [ 72.  -12.    3.9]]
[8.  6.  5.2]
6.0
3.9
[5.2 3.9]
[ 72.  -12.    3.9]


In [53]:
np4=np.array([5,10,15])
np5=np.array([2,4,6])
print(np4+np5)
print(np4-np5)
print(np4*np5)
print(np4/np5)
print(np4**2)
print(np.dot(np4,np5))
print(np4>np5)
print(np4.max())
print(np4.min())
print(np4.sum())
print(np4.sum()+np5.sum())


[ 7 14 21]
[3 6 9]
[10 40 90]
[2.5 2.5 2.5]
[ 25 100 225]
140
[ True  True  True]
15
5
30
42


In [60]:
np5=np.matrix([[2,4,6],[1,3,5]])
print(np5)
print(np5.T)#矩阵的转置
print(np5*np5.T)#转置矩阵求积
print(np5.I)#矩阵的逆
print(np5*np5.I)

[[2 4 6]
 [1 3 5]]
[[2 1]
 [4 3]
 [6 5]]
[[56 44]
 [44 35]]
[[ 1.08333333 -1.33333333]
 [ 0.33333333 -0.33333333]
 [-0.41666667  0.66666667]]
[[ 1.00000000e+00 -1.99840144e-15]
 [-3.88578059e-16  1.00000000e+00]]
